.Dd 2025-03-14
.Dt worldgen 6
.Os Darwin
.Sh NAME
.Nm worldgen
.Nd Traveller world generator.
.Sh SYNOPSIS
.Nm
.Op Fl n Ar NAME
.Op Fl r Ar TYPE
.Op Fl x Ar XXYY
.Nm
.Fl b
.Op Fl r Ar TYPE
.Nm
.Fl h
.Sh DESCRIPTION
Generate the primary world for a star system or a complete subsector using the
rules from 
.Ar Book 3: Worlds and Adventures .
.Sh OPTIONS
The following command line options are available:
.Bl -tag -width -indent
.It Fl b , -subsector
Generate a subsector
.It Fl h , -help
Display help message
.It Fl n , Fl -name\fR=\fINAME\fR
Set the world name.  The default is "No Name".
.It Fl r , -rng\fR=\fITYPE\fR
Set the random number generator type [arc4|ascending|fixed].
The default is "arc4".
.It Fl x , Fl -hex\fR=\fIXXYY\fR
Set the world hex coordinate.  The default is "0101".
.El
