.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 5/12/13               \" DATE 
.Dt worldgen 6      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm worldgen
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.\" Use .Nm macro to designate other names for the documented program.
.Nd Traveller world generator.
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl n Ar NAME
.Op Fl x Ar XXYY
.Sh DESCRIPTION
Generate the primary world for a star system using the rules from 
.Ar Book 3: Worlds and Adventures .
.Sh OPTIONS
The following command line options are available:
.Bl -tag -width -indent
.It Fl h , -help
Display help message
.It Fl n , Fl -name\fR=\fINAME\fR
Set the world name.  The default is "No Name".
.It Fl x , Fl -hex\fR=\fIXXYY\fR
Set the world hex coordinate.  The default is "0101".
.El
.Pp
.Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr a 1 , 
.Xr b 1 ,
.Xr c 1 ,
.Xr a 2 ,
.Xr b 2 ,
.Xr a 3 ,
.Xr b 3 
.\" .Sh BUGS              \" Document known, unremedied bugs 
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner